version: '3.5'

services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: skillsharehub
    ports:
      - 5432:5432
    restart: always
    container_name: ssh_postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
     shh-network:
  redis:
    image: redis
    ports:
      - 6379:6379
    restart: always
    container_name: ssh_redis
    command: redis-server --requirepass redis --save 20 1 --loglevel warning
    volumes:
      - redis:/data
    networks:
     shh-network:

networks:
  shh-network:
    driver: bridge
volumes:
  pgdata:
  redis: